name: "DotnetBuild"
# Controls when the workflow will run
on:
  push:
    branches: [ main,develop/ts-sdk,release/ts-sdk ]
  pull_request:
    branches: [ main,develop/ts-sdk,release/ts-sdk ]
env:
  PROJECT_PATH: 'Tilt_Switch_System/Tilt_Switch_System.sln'
  

jobs:
  deploy:
    name: 'Deploy'
    runs-on: 'windows-latest'
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Install dotnet'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.0.x'

    - name: 'Restore packages'
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: 'Build project'
      run: dotnet build ${{ env.PROJECT_PATH }} 
    - name: 'Get Version'
      id: version
      uses: battila7/get-version-action@v2
